/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package everythig_is_a_graph;

/**
 *
 * @author ACER_
 */
public class name extends javax.swing.JFrame {

    public String n = "";

    /**
     * Creates new form name
     */
    public name() {
        initComponents();
        ButtonTransparent();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        retry = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ruta = new javax.swing.JLabel();
        distancia = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        fondito = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 400));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        retry.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/reload.png"))); // NOI18N
        retry.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                retryMouseClicked(evt);
            }
        });
        getContentPane().add(retry, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 270, 70, 60));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Ruta:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 160, 41));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Distancia mínima: ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 62, 180, 41));

        ruta.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        ruta.setForeground(new java.awt.Color(255, 255, 255));
        ruta.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                rutaAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        getContentPane().add(ruta, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 180, 30));

        distancia.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        getContentPane().add(distancia, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, 180, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, 180, 30));

        fondito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/fondito.gif"))); // NOI18N
        getContentPane().add(fondito, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 1030, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rutaAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_rutaAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_rutaAncestorAdded

    private void retryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_retryMouseClicked

        this.setVisible(false);
        distancia.setText("");
        ruta.setText("");
        this.dispose();
    }//GEN-LAST:event_retryMouseClicked

    public void ButtonTransparent() {
        retry.setOpaque(false);
        retry.setContentAreaFilled(false);
        retry.setBorderPainted(false);

    }

    /*
    
    *
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(name.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(name.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(name.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(name.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new name().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel distancia;
    private javax.swing.JLabel fondito;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton retry;
    public static javax.swing.JLabel ruta;
    // End of variables declaration//GEN-END:variables
}
